---
title: "eda"
author: "Jacinto"
date: "June 14, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
```

# Import Data and Merge  
```{r importData, message = FALSE}
aisles <- read_csv("data/aisles.csv")
depart <- read_csv("data/departments.csv")
orderPrior <- read_csv("data/order_products__prior.csv")
orderTrain <- read_csv("data/order_products__train.csv")
orders <- read_csv("data/orders.csv")
products <- read_csv("data/products.csv")
```

Merge dataset 
```{r}
allDf <- orderPrior %>% 
  bind_rows(orderTrain) %>% 
  left_join(orders, by = "order_id") %>% 
  left_join(products, by = "product_id") %>% 
  left_join(depart, by = "department_id") %>% 
  left_join(aisles, by = "aisle_id")

## Reorder columns for easier viewing  
allDf %<>% select(eval_set, 
                  user_id,
                  order_number,
                  order_dow,
                  order_hour_of_day,
                  days_since_prior_order,
                  reordered,
                  product_name,
                  add_to_cart_order,
                  aisle,
                  department,
                  order_id,
                  product_id,
                  department_id,
                  aisle_id)

## Sort So I can view by user  
allDf %<>% arrange(user_id, order_number, department)

```

Remove the small dataset 
```{r}
rm(aisles, depart, orderPrior, orderTrain, orders, products)
```


# Departments  

* what is in other?  
* purchase per department  

***  
 






# aisles  





# Products  

* items that are purchased in high quantity  
* what is in other aisle 







# User  

* User who bought flu medicine. 
* High purchase users  
* getting action (condom)





# Overview

* Are there any difference between the prior dataset and train dataset?  




















































