---
title: "for h2o dataset"
author: "Jacinto"
date: "July 3, 2017"
output: html_document
---

```{r message = FALSE}
library(tidyverse)
library(magrittr)
library(data.table)
```

```{r}
load("data/trainDF_1.RData")
```


# Clean Data  

Remove columns not needed. convert columns into characters to become factors. Reduce the significant digits on some.   

```{r}
# Remove columns not needed
trainDF[, c("product_id", 
            "user_id", 
            "product_name",
            "department_id",
            "aisle_id") := NULL]


# Round numbers since they are not that accurate
# The significant placement is random  
trainDF[, ':='(diff_days_avg = round(diff_days_avg, 1),
               diff_order_num_avg = round(diff_order_num_avg, 1),
               reordered_prop = round(reordered_prop, 3),
               add_to_cart_order_avg = round(add_to_cart_order_avg, 1),
               n_item_avg = round(n_item_avg, 1),
               order_dow_var = round(order_dow_var, 2),
               order_hod_var = round(order_hod_var, 2),
               order_dspo_var = round(order_dspo_var, 2))]

# Convert reoredered to yes and no to be factored during import 
trainDF[, reordered := factor(reordered, 
                              levels = c(0,1),
                              labels = c("No", "Yes"))]
```


# Export small version to csv  
```{r}
write.csv(trainDF[1:1000000,], file = "data/trainDF1M.csv", row.names = FALSE)
```


