---
title: "randomforest"
author: "Jacinto"
date: "June 26, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(tidyverse)
library(data.table)
library(caret)
library(parallel)
```

# Import Data
```{r}
load("./data/trainDF_1.RData")
```


# Minor Cleanup and Partitioning for Modeling 
```{r}
# Remove columns not needed
trainDF[, c("product_id", 
            "user_id", 
            "product_name",
            "department_id",
            "aisle_id") := NULL]

# Convert cateogry to factors  
trainDF[, ':='(department = as.factor(department),
               aisle = as.factor(aisle))]

trainDF[, reordered := factor(reordered, 
                              levels = c(0,1),
                              labels = c("No", "Yes"))]

# Round numbers since they are not that accurate
# The significant placement is random  
trainDF[, ':='(diff_days_avg = round(diff_days_avg, 1),
               diff_order_num_avg = round(diff_order_num_avg, 1),
               reordered_prop = round(reordered_prop, 3),
               add_to_cart_order_avg = round(add_to_cart_order_avg, 1),
               n_item_avg = round(n_item_avg, 1),
               order_dow_var = round(order_dow_var, 2),
               order_hod_var = round(order_hod_var, 2),
               order_dspo_var = round(order_dspo_var, 2))]

# Convert and split data for modeling 
set.seed(19823)
trainIdx <- createDataPartition(trainDF$reordered, 
                                p = 0.8, list = TRUE)$Resample1

evalDF <- trainDF[-trainIdx, ] %>% copy() %>% setDF()

trainDF <- trainDF[trainIdx, ] %>% setDF()

rm(trainIdx)
```

# Model  
```{r}
# The training set is way to big so have to make a small set  
small <- createDataPartition(trainDF$reordered, p = 0.1)$Resample1
```



```{r}
fitrf <- train(reordered~.,
               data = trainDF[small,],
               method = "rf",
               metric = "Accuracy",
               tuneGrid = expand.grid(mtry = 4),
               ntree = 50,
               trControl = trainControl(method = "cv",
                                        number = 5,
                                        verboseIter = TRUE))
```



