---
title: "Wrangling Data"
author: "Jacinto"
date: "June 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message = FALSE}
library(tidyverse)
library(magrittr)
library(data.table)
```
```
# TODO:  
  1. Maybe add variance for diff_days. Nah each product has a large range
  3. a feature that is "next purchase reordered"?. This is to deal with products that were recently bought and then reordered during training set. 
  4. a feature that is "was it ever reordered in user lifetime"?
  5. Proportion of the product of interest were immediately reordered or the average reordered proportion for product   
  5. A binary feature that ask if product was first time recent order. Was the product brougt for the first time in the most recent past order. So right before train/test order. 

```



# Import Data  
```{r}
products <- fread("./data/products.csv")
aisles <- fread("./data/aisles.csv")
depart <- fread("./data/departments.csv")
orders <- fread("./data/orders.csv")
orderPrior <- fread("./data/order_products__prior.csv")
orderTrain <- fread("./data/order_products__train.csv")
```


# Calculate some Features  
```{r}
# Set days_since_prior_order to NA since cumsum cannot handle NA
orders[is.na(days_since_prior_order), days_since_prior_order := 0]

# Add the absolute days for users 
# Need to sort by user and order_number such that days are in order to be added
setorder(orders, user_id, order_number)

           # The cumalative sum of the days after each order 
orders[, ':='(abs_days = cumsum(days_since_prior_order),
           # The number of order a user has made including the train/test order
           order_number_max = max(order_number), 
           # User's ordering habits and consistency 
           # Not sure if this is useful when user's # of orders are different
           # Variance of ordering day of week
           order_dow_var = var(order_dow),
           # Variance of ordering hour of day  
           order_hod_var = var(order_hour_of_day),
           # Variance of days since prior order 
           order_dspo_var = var(days_since_prior_order)),
    by = user_id]

# Number of items in each order 
n_item_order <- orderPrior[,.(n_item = .N), by = order_id]

# Merge n_item_order to orders
orders <- n_item_order[orders, on = "order_id"]

# Save memory
rm(n_item_order)
```


# Merge Data
```{r}
# Combine products and its aisle and department names 
prod_ais_dep <- products %>%
  merge(aisles, by = "aisle_id", all.x = TRUE) %>% 
  merge(depart, by = "department_id", all.x = TRUE)

# Save memory 
rm(products, aisles, depart)
gc()
```

```{r}
# Separate into training and testing set
orderTr <- subset(orders, eval_set == "train")
orderTs <- subset(orders, eval_set == "test")
# Remove columns not needed to save memory
orderTr[, c("n_item",
            "order_number",
            "order_dow",
            "order_hour_of_day"):=NULL]
orderTs[, c("n_item",
            "order_number",
            "order_dow",
            "order_hour_of_day") := NULL]

# Combine prior orders and its product together  
orderPr <- orders %>% 
  merge(orderPrior, by = "order_id")

# Remove columns not needed to save memory  
orderPr[,c("order_id", 
           "eval_set",
           "order_dow",
           "order_hour_of_day",
           "days_since_prior_order",
           "order_dow_var",
           "order_hod_var",
           "order_dspo_var"):=NULL]

rm(orders, orderPrior)
gc()
```


# Summarize Data
```{r}
# Return the number of orders from the latest order number to the first order
# excluding the train/test set order number 
order_diff <- function(late, first){
  # Subtract train/test order number with first product order with correction -1
  tmp_diff <- late - first - 1
  # Will cause an error if product was first time ordered during or the one
  # before train/test order
  if((tmp_diff) <= 0){
    return(1)
  }
  return(tmp_diff)
}

# Was product immediately reordered.
ordered_next_fun <- function(x){
  if(length(x) == 1){return(0)}
  if(diff(sort(x)[1:2], 1) == 1){return(1)}
  return(0)
}

```

```{r}
# Needs the order for each user to be in order
setorder(orderPr, user_id, product_id, order_number)
          # Days difference in between product purchase
orderPr[, ':='(diff_days = c(0, diff(abs_days,1)),
               # The gap between each product's reorder
               diff_order_num = c(0, diff(order_number))), 
    by = .(user_id, product_id)]

# Summary of prior data
                   # The average in between days product purchase exclude 1st  
priorSum <- orderPr[, .(diff_days_avg = sum(diff_days)/ifelse(.N >1, .N-1, 1),
                   # The average order_num gap in between product's reorder
                   diff_order_num_avg = (sum(diff_order_num)/
                                           ifelse(.N > 1, .N-1, 1)),
                   # Subtract current order with most recent product order
                   order_since_last = (order_number_max[[1]] -
                                          max(order_number)),
                   # Number of times product was reorodered 
                   reordered_num = sum(reordered),
                   # Proportion of times product was reordered
                   reordered_prop = (sum(reordered)/
                                       order_diff(order_number_max[[1]],
                                                  min(order_number))),
                   # Was the product reorodered immediately after 1st order
                   reordered_next = ordered_next_fun(order_number),
                   # Average number of product added to cart
                   add_to_cart_order_avg = mean(add_to_cart_order),
                   # Average number of item in cart when product was purchased
                   n_item_avg = mean(n_item),
                   # Last absolute day product was order
                   last_reordered_day = max(abs_days)),
               by = .(user_id, product_id)]

# Save memory 
rm(orderPr)
gc()

trainDF <- merge(priorSum[user_id %in% unique(orderTr$user_id)], 
                 orderTr, 
                 by = c("user_id"), 
                 all = TRUE)
trainDF %<>% merge(orderTrain,
                   by = c("order_id", "product_id"),
                   all = TRUE) 


testDF <- merge(priorSum[user_id %in% unique(orderTs$user_id)],
                orderTs,
                by = c("user_id"),
                all.y = TRUE)

# Remove to save memory
rm(priorSum, orderTr, orderTs, orderTrain)
gc()

# Combine with product's name, department, aisle 
trainDF %<>% merge(prod_ais_dep, by = "product_id")

testDF %<>% merge(prod_ais_dep, by = "product_id")

# Remove to save memory 
rm(prod_ais_dep)

# Days since last pruchase or the product
trainDF[, days_since_last := abs_days - last_reordered_day]
testDF[, days_since_last := abs_days - last_reordered_day]

# First time ordered before prediction order, 1 = TRUE
trainDF$first_order <- 0
testDF$first_order <- 0 

trainDF[order_since_last == 1 & reordered_num == 0, "first_order"] <- 1
testDF[order_since_last == 1 & reordered_num == 0, "first_order"] <- 1

# Remove columns that aren't needed
trainDF[, c("abs_days", 
            "last_reordered_day", 
            "eval_set", 
            "order_id", 
            "add_to_cart_order") := NULL]

testDF[, c("abs_days", "last_reordered_day", "eval_set") := NULL]

setorder(trainDF, user_id, product_id)
setorder(testDF, user_id, product_id)
```

# Fix NAs
```{r}
# Remove purchases that are new since no way to predict new purchases
# 555,793 rows were elimated
trainDF <- trainDF[!is.na(reordered_num)]
# reordered NA means that they weren't reordered for the most recent order
trainDF[is.na(reordered), reordered := 0]
```

# Write
```{r}
# save(trainDF, file = "./data/trainDF_1.RData")
# save(testDF, file = "./data/testDF_1.RData")
```










































